_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_episode_storage:
    value: None
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 1.0000000e+00  2.0000000e-02  5.0078177e-01  0.0000000e+00
           -5.0000000e-01  6.1232343e-17 -1.0000000e+00]
          [ 1.0000000e+00 -1.3081485e-01  2.0000000e-02  3.8169035e-01
            0.0000000e+00  1.0000000e+00 -2.0576134e-16]
          [ 1.0000000e+00  6.4344007e-01 -2.0000000e-02 -3.8118505e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  4.5911449e-01 -2.0000000e-02 -4.0000001e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00 -2.0000000e-02 -4.6824902e-01  2.2204460e-16
            4.0415692e-01  2.8327693e-16  1.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x16e43ee60>
_n_calls:
    value: 0
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 50000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.0
        e:
            czngwm7bhmgrslzvhloeq23grc2u9l3o:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "4294967296"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "252249575424"
                email: ccloutier@uwaterloo.ca
                executable: /Users/charlottecloutier/Documents/4A/venv/bin/python3
                host: Charlottes-MacBook-Pro.local
                memory:
                    total: "19327352832"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/charlottecloutier/Documents/4A/ECE457C/asg3/train.py
                python: CPython 3.10.0
                root: /Users/charlottecloutier/Documents/4A/ECE457C/asg3
                startedAt: "2025-07-23T19:35:46.674218Z"
                writerId: czngwm7bhmgrslzvhloeq23grc2u9l3o
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 22
                - 34
                - 35
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Discrete(3)
algo:
    value: DQN
batch_norm_stats:
    value: '[]'
batch_norm_stats_target:
    value: '[]'
batch_size:
    value: 32
buffer_size:
    value: 1000000
device:
    value: cpu
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x16e43f280>
env_id:
    value: intersection-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 5000
exploration_final_eps:
    value: 0.05
exploration_fraction:
    value: 0.1
exploration_initial_eps:
    value: 1
exploration_rate:
    value: 0
exploration_schedule:
    value: <function get_linear_fn.<locals>.func at 0x16e49e8c0>
gamma:
    value: 0.99
gradient_steps:
    value: 1
learning_rate:
    value: 0.0001
learning_starts:
    value: 100
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x16e49f6d0>
max_grad_norm:
    value: 10
n_envs:
    value: 1
n_eval_episodes:
    value: 10
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (15, 7), float32)
optimize_memory_usage:
    value: "False"
policy:
    value: |-
        DQNPolicy(
          (q_net): QNetwork(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (q_net): Sequential(
              (0): Linear(in_features=105, out_features=64, bias=True)
              (1): ReLU()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): ReLU()
              (4): Linear(in_features=64, out_features=3, bias=True)
            )
          )
          (q_net_target): QNetwork(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (q_net): Sequential(
              (0): Linear(in_features=105, out_features=64, bias=True)
              (1): ReLU()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): ReLU()
              (4): Linear(in_features=64, out_features=3, bias=True)
            )
          )
        )
policy_class:
    value: <class 'stable_baselines3.dqn.policies.DQNPolicy'>
policy_kwargs:
    value: '{}'
q_net:
    value: |-
        QNetwork(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (q_net): Sequential(
            (0): Linear(in_features=105, out_features=64, bias=True)
            (1): ReLU()
            (2): Linear(in_features=64, out_features=64, bias=True)
            (3): ReLU()
            (4): Linear(in_features=64, out_features=3, bias=True)
          )
        )
q_net_target:
    value: |-
        QNetwork(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (q_net): Sequential(
            (0): Linear(in_features=105, out_features=64, bias=True)
            (1): ReLU()
            (2): Linear(in_features=64, out_features=64, bias=True)
            (3): ReLU()
            (4): Linear(in_features=64, out_features=3, bias=True)
          )
        )
replay_buffer:
    value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x16e43f310>
replay_buffer_class:
    value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
    value: '{}'
run_index:
    value: 0
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1753299347288180000
target_update_interval:
    value: 10000
tau:
    value: 1
tensorboard_log:
    value: ./rl_logs/DQN_intersection-v0_run_0
total_timesteps:
    value: 50000
train_freq:
    value: 'TrainFreq(frequency=4, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
    value: "False"
use_sde_at_warmup:
    value: "False"
verbose:
    value: 0
