_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 1.          0.7561674   0.          0.3125      0.        ]
          [ 1.          0.10901305  0.33333334 -0.04875536  0.        ]
          [ 1.          0.22500673  0.33333334 -0.01939341  0.        ]
          [ 1.          0.33027458  0.         -0.04213434  0.        ]
          [ 1.          0.44967112  0.33333334 -0.03492263  0.        ]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x1794cd750>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 50000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.0
        e:
            rhh1aa46dvbnwd2lcha99gwiobh40o75:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "4294967296"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "252229599232"
                email: ccloutier@uwaterloo.ca
                executable: /Users/charlottecloutier/Documents/4A/venv/bin/python3
                host: Charlottes-MacBook-Pro.local
                memory:
                    total: "19327352832"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/charlottecloutier/Documents/4A/ECE457C/asg3/train.py
                python: CPython 3.10.0
                root: /Users/charlottecloutier/Documents/4A/ECE457C/asg3
                startedAt: "2025-07-23T19:28:41.318828Z"
                writerId: rhh1aa46dvbnwd2lcha99gwiobh40o75
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 22
                - 34
                - 35
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Discrete(5)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x14b295b40>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x1794cceb0>
env_id:
    value: highway-fast-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 5000
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x14b295a20>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_eval_episodes:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (5, 5), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=25, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=25, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=5, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x1794cccd0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
run_index:
    value: 0
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1753298921852157000
target_kl:
    value: None
tensorboard_log:
    value: ./rl_logs/PPO_highway-fast-v0_run_0
total_timesteps:
    value: 50000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
